vim.keymap.set('n', '<c-h>', '<cmd><C-U>TmuxNavigateLeft<CR>')
vim.keymap.set('n', '<c-j>', '<cmd><C-U>TmuxNavigateDown<CR>')
vim.keymap.set('n', '<c-k>', '<cmd><C-U>TmuxNavigateUp<CR>')
vim.keymap.set('n', '<c-l>', '<cmd><C-U>TmuxNavigateRight<CR>')
vim.keymap.set('n', '<c-\\>', '<cmd><C-U>TmuxNavigatePrevious<CR>')
